require("nvimConfig.remap")
vim.cmd('colorscheme github_dark_high_contrast')
vim.cmd('set mouse=a')
vim.cmd('set number')
vim.cmd('set relativenumber')
vim.cmd('set cursorline')
vim.cmd('set tabstop=4')
vim.cmd('set shiftwidth=4')
vim.cmd('set autoindent')

