require("nvimConfig.remap")
vim.cmd('colorscheme elflord')
vim.cmd('set mouse=a')
vim.cmd('set number')
vim.cmd('set relativenumber')
vim.cmd('set tabstop=4')
vim.cmd('set shiftwidth=4')
vim.cmd('set autoindent')
vim.cmd('set cursorline')
