require("nvimConfig.remap")
require("ibl").setup()
vim.cmd('colorscheme tokyonight')
-- vim.cmd('set mouse=a')
vim.cmd('set number')
vim.cmd('set relativenumber')
vim.cmd('set cursorline')
vim.cmd('set tabstop=2')
vim.cmd('set shiftwidth=2')
vim.cmd('set autoindent')
